export const WEBSITE_NAME = "Vidbox";
export const WEBSITE_URL = "vidbox.to";
export const WEBSITE_FULL_URL = `https://${WEBSITE_URL}`;
export const DISCORD_URL = "https://discord.gg/";
export const DOWNLOAD_APK = "https://cinehd.xyz/download/index.html";

export interface Provider {
  name: string;
  url: string;
  countryUrl: string;
  idType: string;
  urlFormat: string;
  extraParams?: string;
  autoplaySupport?: boolean;
}

export const AUTOPLAY_PROVIDERS: Provider[] = [
  {
    name: "Vidsrc",
    url: "https://vidsrc.net/embed/tv/",
    countryUrl: "https://flagsapi.com/US/flat/24.png",
    idType: "tmdb",
    urlFormat: "id/season-episode",
    extraParams: "?referrer=none"
  },
  {
    name: "4K",
    url: "https://player.videasy.net/tv/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode"
  },
  {
    name: "Echo",
    url: "https://vidlink.pro/tv/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode?style",
    extraParams: "?primaryColor=white&secondaryColor=white&iconColor=white&title=false&poster=true&autoplay=true"
  },
  {
    name: "Vidfast",
    url: "https://vidfast.pro/tv/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode?autoplay=true"
  }
];

export const PROVIDERS_TV: Provider[] = [

  {
    name: "Max",
    url: "https://ythd.org/embed/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season-episode",
  },

  {
    name: "4K",
    url: "https://player.videasy.net/tv/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "Premium",
    url: "https://player.vidsrc.co/embed/tv/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "WTF(4K)",
    url: "https://vidsrc.wtf/api/1/tv/?id=",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id&s=season&e=episode",
  },
  {
    name: "Orion",
    url: "https://vidsrc.dev/embed/tv/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "imdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "Duke",
    url: "https://embed.su/embed/tv/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "imdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "Vidsrc",
    url: "https://vidsrc.net/embed/tv/",
    countryUrl: "https://flagsapi.com/US/flat/24.png",
    idType: "tmdb",
    urlFormat: "id/season-episode",
    extraParams: "?referrer=none",
  },

  {
    name: "Echo",
    url: "https://vidlink.pro/tv/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode?style",
    extraParams:
      "?primaryColor=white&secondaryColor=white&iconColor=white&title=false&poster=true&autoplay=true",
  },
  {
    name: "Asia",
    url: "https://autoembed.cc/embed/player.php?id=",
    countryUrl: `https://flagsapi.com/IN/flat/24.png`,
    idType: "imdb",
    urlFormat: "id&s=season&e=episode",
  },
  {
    name: "Bravo",
    url: "https://moviesapi.club/tv/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode",
  },

  {
    name: "Atlas",
    url: "https://vidsrc.cc/v2/embed/tv/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "imdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "Golf",
    url: "https://player.autoembed.cc/embed/tv/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "Rip",
    url: "https://vidsrc.rip/embed/tv/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "Alpha",
    url: "https://player.smashy.stream/tv/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "imdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "Delta",
    url: "https://www.vidstream.site/embed/tv/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "Lima",
    url: "https://vidsrc.vip/embed/tv/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "111",
    url: "https://111movies.com/tv/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "Jade",
    url: "https://superflixapi.dev/serie/",
    countryUrl: `https://flagsapi.com/PT/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "French",
    url: "https://play.frembed.pro/api/serie.php?id=",
    countryUrl: `https://flagsapi.com/FR/flat/24.png`,
    idType: "imdb",
    urlFormat: "id&sa=season&epi=episode",
  },
  {
    name: "Spanish",
    url: "https://ythd.org/embed/",
    countryUrl: `https://flagsapi.com/ES/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season-episode",
  },
  {
    name: "Viet",
    url: "https://viet.autoembed.cc/tv/",
    countryUrl: `https://flagsapi.com/VN/flat/24.png`,
    idType: "imdb",
    urlFormat: "id/season/episode",
  },
  {
    name: "Rive",
    url: "https://rivestream.org/embed?type=tv&id=",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id&season=season&episode=episode",
  },
  {
    name: "Vidjoy",
    url: "https://vidjoy.pro/embed/tv/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode?autoplay=true",
  },
  {
    name: "Vidfast",
    url: "https://vidfast.pro/tv/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode?autoplay=true",
  },
  {
    name: "Flicky",
    url: "https://flicky.host/embed/tv/?id=",
    countryUrl: `https://flagsapi.com/IN/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id/season/episode",
  },
];

export const PROVIDERS_MOVIE = [

  {
    name: "Max",
    url: "https://ythd.org/embed/{id}",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "4K",
    url: "https://player.videasy.net/movie/{id}",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Premium",
    url: "https://player.vidsrc.co/embed/movie/{id}",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "WTF(4K)",
    url: "https://vidsrc.wtf/api/4/movie/?id={id}",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Orion",
    url: "https://vidsrc.dev/embed/movie/{id}",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "imdb",
    urlFormat: "id",
  },
  {
    name: "Duke",
    url: "https://embed.su/embed/movie/{id}",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "imdb",
    urlFormat: "id",
  },
  {
    name: "Echo",
    url: "https://vidlink.pro/movie/{id}",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "?style",
    extraParams:
      "?primaryColor=white&secondaryColor=white&iconColor=white&title=false&poster=true&autoplay=true",
  },
  {
    name: "Asia",
    url: "https://autoembed.cc/embed/player.php?id={id}",
    countryUrl: `https://flagsapi.com/IN/flat/24.png`,
    idType: "imdb",
    urlFormat: "id",
  },
  {
    name: "Bravo",
    url: "https://moviesapi.club/movie/{id}",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Atlas",
    url: "https://vidsrc.cc/v2/embed/movie/{id}",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "imdb",
    urlFormat: "id",
  },
  {
    name: "Golf",
    url: "https://player.autoembed.cc/embed/movie/{id}",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Rip",
    url: "https://vidsrc.rip/embed/movie/{id}",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Alpha",
    url: "https://player.smashy.stream/movie/{id}",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "imdb",
    urlFormat: "id",
  },
  {
    name: "Delta",
    url: "https://www.vidstream.site/embed/movie/{id}",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Lima",
    url: "https://vidsrc.vip/embed/movie/{id}",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "111",
    url: "https://111movies.com/movie/{id}",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Jade",
    url: "https://superflixapi.dev/filme/{id}",
    countryUrl: `https://flagsapi.com/PT/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "French",
    url: "https://frembed.pro/api/film.php?id={id}",
    countryUrl: `https://flagsapi.com/FR/flat/24.png`,
    idType: "imdb",
    urlFormat: "id",
  },
  {
    name: "Spanish",
    url: "https://ythd.org/embed/{id}",
    countryUrl: `https://flagsapi.com/ES/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Viet",
    url: "https://viet.autoembed.cc/movie/{id}",
    countryUrl: `https://flagsapi.com/VN/flat/24.png`,
    idType: "imdb",
    urlFormat: "id",
  },
  {
    name: "Rive",
    url: "https://rivestream.org/embed?type=movie&id={id}",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Vidjoy",
    url: "https://vidjoy.pro/embed/movie/{id}?autoplay=true",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Vidfast",
    url: "https://vidfast.pro/movie/{id}?autoplay=true",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
  {
    name: "Flicky",
    url: "https://flicky.host/embed/movie/?id={id}",
    countryUrl: `https://flagsapi.com/IN/flat/24.png`,
    idType: "tmdb",
    urlFormat: "id",
  },
];

export const ANIME_PROVIDERS = [
  {
    name: "Max",
    url: "https://player.videasy.net/anime/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "anilist",
    urlFormat: "id/episode?dub=true",
  },
  {
    name: "Orion",
    url: "https://player.videasy.net/anime/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "anilist",
    urlFormat: "id/episode?dub=false",
  },
  {
    name: "Duke",
    url: "embed.su/embed/anime/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "mal",
    urlFormat: "id/episode",
  },
  {
    name: "Echo",
    url: "vidlink.pro/anime/",
    countryUrl: `https://flagsapi.com/US/flat/24.png`,
    idType: "anilist",
    urlFormat: "id/episode",
    extraParams:
      "?primaryColor=white&secondaryColor=white&iconColor=white&title=false&poster=true&autoplay=true",
  },
  {
    name: "Asia",
    url: "autoembed.cc/embed/player.php?id=",
    countryUrl: `https://flagsapi.com/IN/flat/24.png`,
    idType: "mal",
    urlFormat: "id&e=episode",
  },
  {
    name: "Bravo",
    url: "https://moviesapi.club/anime/",
    countryUrl: `https://flagsapi.com/GB/flat/24.png`,
    idType: "anilist",
    urlFormat: "id/episode",
  },
];

export const DEFAULT_MOVIE_PROVIDER = PROVIDERS_MOVIE[0];
export const DEFAULT_TV_PROVIDER = PROVIDERS_TV[0];
export const DEFAULT_ANIME_PROVIDER = ANIME_PROVIDERS[0];

export const country = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AS", label: "American Samoa" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AI", label: "Anguilla" },
  { value: "AQ", label: "Antarctica" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AW", label: "Aruba" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BM", label: "Bermuda" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brazil" },
  { value: "BN", label: "Brunei Darussalam" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CV", label: "Cape Verde" },
  { value: "KY", label: "Cayman Islands" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo" },
  { value: "CD", label: "Congo, Democratic Republic" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Cote d'Ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czech Republic" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "ET", label: "Ethiopia" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Greece" },
  { value: "GL", label: "Greenland" },
  { value: "GD", label: "Grenada" },
  { value: "GU", label: "Guam" },
  { value: "GT", label: "Guatemala" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hong Kong" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "KP", label: "Korea, Democratic People's Republic" },
  { value: "KR", label: "Korea, Republic" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Lao People's Democratic Republic" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MO", label: "Macao" },
  { value: "MK", label: "Macedonia" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestine" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "PR", label: "Puerto Rico" },
  { value: "QA", label: "Qatar" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "RW", label: "Rwanda" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "Sao Tome and Principe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SZ", label: "Swaziland" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syrian Arab Republic" },
  { value: "TW", label: "Taiwan" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" },
  { value: "TG", label: "Togo" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Turkey" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnam" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
];
