export const COUNTRIES = [
  { value: "korean", label: "Korean" },
  { value: "chinese", label: "Chinese" },
  { value: "japanese", label: "Japanese" },
  { value: "thailand", label: "Thailand" },
  { value: "taiwanese", label: "Taiwanese" },
  { value: "indian", label: "Indian" },
  { value: "hong-kong", label: "Hong Kong" },
  { value: "other-asia", label: "Other Asia" },
];

export const GENRES =
[
  { value: "drama", label: "Drama" },
  { value: "romance", label: "Romance" },
  { value: "comedy", label: "Comedy" },
  { value: "action", label: "Action" },
  { value: "mystery", label: "Mystery" },
  { value: "thriller", label: "Thriller" },
  { value: "fantasy", label: "Fantasy" },
  { value: "historical", label: "Historical" },
  { value: "youth", label: "Youth" },
  { value: "life", label: "Life" },
  { value: "crime", label: "Crime" },
  { value: "family", label: "Family" },
  { value: "web-series", label: "Web Series" },
  { value: "school", label: "School" },
  { value: "friendship", label: "Friendship" },
  { value: "suspense", label: "Suspense" },
  { value: "horror", label: "Horror" },
  { value: "novel", label: "Novel" },
  { value: "investigation", label: "investigation" },
  { value: "adventure", label: "Adventure" },
  { value: "miniseries", label: "Miniseries" },
  { value: "melodrama", label: "melodrama" },
  { value: "bl", label: "BL" },
  { value: "supernatural", label: "Supernatural" },
  { value: "detective", label: "Detective" },
  { value: "business", label: "Business" },
  { value: "manga", label: "Manga" },
  { value: "variety", label: "Variety" },
  { value: "medical", label: "Medical" },
  { value: "food", label: "Food" },
  { value: "sci-fi", label: "Sci-fi" },
  { value: "music", label: "Music" },
  { value: "variety-show", label: "Variety show" },
  { value: "sports", label: "Sports" },
  { value: "psychological", label: "Psychological" },
  { value: "wuxia", label: "Wuxia" },
  { value: "musical", label: "Musical" },
  { value: "revenge", label: "Revenge" },
  { value: "law", label: "Law" },
  { value: "martial-arts", label: "Martial Arts" },
  { value: "war", label: "War" },
  { value: "political", label: "political" },
  { value: "documentary", label: "Documentary" },
  { value: "murder", label: "Murder" },
  { value: "time-travel", label: "Time Travel" },
  { value: "workplace", label: "Workplace" },
  { value: "childhood", label: "Childhood" },
  { value: "history", label: "History" },
  { value: "lgbtq+", label: "LGBTQ+" },
  { value: "tokusatsu", label: "Tokusatsu" },
  { value: "cohabitation", label: "Cohabitation" },
  { value: "mature", label: "Mature" },
  { value: "amnesia", label: "Amnesia" },
  { value: "military", label: "Military" },
  { value: "cold-man", label: "Cold Man" },
  { value: "teamwork", label: "Teamwork" },
  { value: "period", label: "Period" },
  { value: "betrayal", label: "Betrayal" },
  { value: "serial-killer", label: "Serial Killer" },
  { value: "accident", label: "Accident" },
  { value: "hidden-identity", label: "Hidden Identity" },
  { value: "corruption", label: "Corruption" },
  { value: "trauma", label: "Trauma" },
  { value: "science-fiction", label: "Science-Fiction" },
  { value: "survival", label: "Survival" },
  { value: "tragedy", label: "Tragedy" },
  { value: "gangster", label: "Gangster" },
  { value: "reality-show", label: "Reality Show" },
  { value: "legal", label: "legal" },
  { value: "modern", label: "Modern" },
  { value: "conspiracy", label: "Conspiracy" },
  { value: "human", label: "Human" },
  { value: "based-on-true-story", label: "Based on True Story" },
  { value: "zombie", label: "Zombie" },
  { value: "contract-relationship", label: "Contract Relationship" },
  { value: "slice-of-life", label: "Slice of Life" },
  { value: "sitcom", label: "Sitcom" },
  { value: "criminal", label: "Criminal" },
  { value: "neighbours", label: "Neighbours" },
  { value: "lesbian", label: "Lesbian" },
  { value: "demon", label: "Demon" },
  { value: "bromance", label: "Bromance" },
  { value: "manhua", label: "Manhua" },
  { value: "resurrection", label: "Resurrection" },
  { value: "bodyguard", label: "Bodyguard" },
  { value: "noir", label: "Noir" },
  { value: "romantic", label: "romantic" },
  { value: "period-drama", label: "Period Drama" },
  { value: "disaster", label: "Disaster" },
  { value: "sismance", label: "Sismance" },
  { value: "webtoon", label: "Webtoon" },
  { value: "drama-romance", label: "Drama, Romance" },
  { value: "reality", label: "Reality" },
  { value: "kidnapping", label: "Kidnapping" },
  { value: "animals", label: "Animals" },
  { value: "animal", label: "Animal" },
  { value: "biography", label: "Biography" },
  { value: "police", label: "police" },
  { value: "fashion", label: "Fashion" },
  { value: "vampire", label: "Vampire" },
  { value: "magic", label: "Magic" },
  { value: "medical-drama", label: "Medical drama" },
  { value: "underworld", label: "Underworld" },
  { value: "rich-man", label: "Rich Man" },
  { value: "curse", label: "Curse" },
  { value: "entertainment", label: "Entertainment" },
  { value: "historical-drama", label: "Historical Drama" },
  { value: "high-school", label: "High School" },
  { value: "harem", label: "Harem" },
  { value: "robot", label: "Robot" },
  { value: "short", label: "Short" },
  { value: "samurai", label: "Samurai" },
  { value: "espionage", label: "Espionage" },
  { value: "exorcism", label: "Exorcism" },
  { value: "monster", label: "Monster" },
  { value: "fantasy-romance", label: "Fantasy, Romance" },
  { value: "comedy-romance", label: "Comedy, Romance" },
  { value: "love", label: "Love" },
  { value: "mafia", label: "Mafia" },
  { value: "alien", label: "Alien" },
  { value: "crime-drama", label: "Crime drama" },
  { value: "crime-thriller", label: "Crime Thriller" },
  { value: "teen", label: "Teen" },
  { value: "sport", label: "sport" },
  { value: "women", label: "Women" },
  { value: "coma", label: "Coma" },
  { value: "gumiho", label: "Gumiho" },
  { value: "phobia", label: "Phobia" },
  { value: "swordsman", label: "Swordsman" },
  { value: "warrior", label: "Warrior" },
  { value: "terrorist", label: "Terrorist" },
  { value: "modern-romance", label: "Modern romance" },
  { value: "renzoku", label: "Renzoku" },
  { value: "based-on-a-comic", label: "Based on a Comic" },
  { value: "school-life", label: "School Life" },
  { value: "game", label: "Game" },
  { value: "nature", label: "Nature" },
  { value: "artificial-intelligence", label: "Artificial Intelligence" },
  { value: "witch", label: "Witch" },
  { value: "power-struggle", label: "Power Struggle" },
  { value: "romance-youth", label: "Romance, Youth" },
  { value: "josei", label: "Josei" },
  { value: "school-comedy", label: "School comedy" },
  { value: "romantic-comedy", label: "romantic comedy" },
  { value: "ancient-wuxia-fantasy-rpg", label: "Ancient wuxia fantasy (RPG)" },
  { value: "reality-tv", label: "Reality TV" },
  { value: "professional", label: "Professional" },
  { value: "chinese", label: "Chinese" },
  { value: "human-drama", label: "Human drama" },
  { value: "action-war", label: "Action War" },
  { value: "action-police", label: "Action Police" },
  { value: "scholar", label: "Scholar" },
  { value: "religion", label: "Religion" },
  { value: "deity", label: "Deity" },
  { value: "fairy", label: "Fairy" },
  { value: "goryeo-dynasty", label: "Goryeo Dynasty" },
  { value: "drama-romance-thriller", label: "Drama, Romance, Thriller" },
  { value: "drama-romance-youth", label: "Drama, Romance, Youth" },
  { value: "mystery-thriller", label: "Mystery, Thriller" },
  { value: "documentation", label: "Documentation" },
  { value: "xianxia", label: "Xianxia" },
  { value: "historical-fiction", label: "Historical Fiction" },
  { value: "light-comedy", label: "light comedy" },
  { value: "idol-drama", label: "Idol Drama" },
  { value: "water-sports", label: "Water Sports" },
  { value: "audition", label: "audition" },
  { value: "modern-drama", label: "modern drama" },
  { value: "airline", label: "airline" },
  { value: "disability", label: "Disability" },
  { value: "manga-live-action", label: "Manga live action" },
  { value: "seinen", label: "Seinen" },
  { value: "jidaigeki", label: "jidaigeki" },
  { value: "pre-modern", label: "Pre-modern" },
  { value: "medicine", label: "Medicine" },
  { value: "classic", label: "classic" },
  { value: "rebellion", label: "Rebellion" },
  { value: "drama-24", label: "Drama 24" },
  { value: "rpg", label: "RPG" },
  { value: "indie", label: "Indie" },
  { value: "japanese", label: "Japanese" },
  { value: "erotic", label: "Erotic" },
  { value: "cop", label: "Cop" },
  { value: "arthouse", label: "Arthouse" },
  { value: "mother-son", label: "Mother & Son" },
  { value: "yuri", label: "Yuri" },
  { value: "fiction", label: "Fiction" },
  { value: "cooking", label: "Cooking" },
  { value: "western", label: "Western" },
  { value: "omnibus", label: "Omnibus" },
  { value: "werewolf", label: "Werewolf" },
  { value: "programmer", label: "Programmer" },
  { value: "animation", label: "Animation" },
  { value: "hypnotism", label: "Hypnotism" },
  { value: "mythology", label: "Mythology" },
  { value: "triad", label: "Triad" },
  { value: "soulmates", label: "Soulmates" },
  { value: "tragic-past", label: "Tragic Past" },
  { value: "gore", label: "Gore" },
  { value: "conglomerate", label: "Conglomerate" },
  { value: "comedy-drama-romance", label: "Comedy, Drama, Romance" },
  { value: "action-drama-mystery-thriller", label: "Action, Drama, Mystery, Thriller" },
  { value: "drama-mystery-romance-thriller", label: "Drama, Mystery, Romance, Thriller" },
  { value: "melodrama-romance", label: "Melodrama, Romance" },
  { value: "drama-mystery-thriller", label: "Drama, Mystery, Thriller" },
  { value: "fantasy-romance-thriller", label: "Fantasy, Romance, Thriller" },
  { value: "drama-lgbtq+-romance-youth", label: "Drama, LGBTQ+, Romance, Youth" },
  { value: "drama-historical-romance", label: "Drama, Historical, Romance" },
  { value: "comedy-family-historical-romance", label: "Comedy, Family, Historical, Romance" },
  { value: "drama-family", label: "Drama, Family" },
  { value: "action-historical-mystery-romance", label: "Action, Historical, Mystery, Romance" }
]

export const TYPES = [
  { value: "drama", label: "Drama" },
  { value: "movie", label: "Movies" },
  // { value: "kshow", label: "KShow" },
];